name: Coverage

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cov-tk:
    name: Harness Tests Coverage
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup public GitHub runner
        uses: ./.github/actions/setup-public-gh-runner
        with:
          zig: 'true'
          kcov: 'true'
          setup-recipe: setup-linux-x86-gcc

      - uses: ./.github/actions/build-fd-tk-libs

      - name: Run coverage
        run: just test-cov-tk-linux-x86

      - name: Upload coverage summary
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-tk
          path: build/coverage/tk/coverage-summary.json

  cov-fd:
    name: Engine Tests Coverage
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Firedancer test environment
        uses: ./.github/actions/setup-fd-test
        with:
          compiler: clang
          compiler-version: '18'
          configure-hugepages: 'false'

      - name: Install LLVM coverage tools
        run: just setup-coverage-linux-x86-clang

      - name: Run coverage
        run: just test-cov-fd-linux-x86-clang

      - name: Upload coverage summary
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-fd
          path: build/coverage/fd/coverage-summary.json
